# .github/workflows/generate-mapping.yml
name: Generate mapping.json

on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        working-directory: ./scripts
        run: npm install

      - name: Generate mapping.json
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY:       ${{ github.repository }}
        run: node generateMapping.js

      - name: Commit mapping.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mapping.json
          git diff --quiet && echo "No changes" || git commit -m "chore: update mapping.json"
          git push
