name: Generate mapping.json

on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: List repo contents (debug)
        run: |
          echo "=== ROOT CONTENTS ==="
          ls -R .

      - name: List images/ folder (debug)
        run: |
          echo "=== images/ CONTENTS ==="
          ls -R images || echo "images/ not found!"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        working-directory: ./scripts
        run: npm install

      - name: Show scripts folder (debug)
        working-directory: ./scripts
        run: |
          echo "=== scripts/ CONTENTS ==="
          ls -R .

      - name: Generate mapping.json (debug logs)
        working-directory: ./scripts
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY:       ${{ github.repository }}
        run: |
          echo "Running generateMapping.js..."
          node generateMapping.js
          echo "=== GENERATED mapping.json ==="
          cat ../mapping.json || echo "mapping.json not found!"

      - name: Commit mapping.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mapping.json
          git diff --quiet || git commit -m "chore: update mapping.json"
          git push

